# Dockerfile
FROM node:22-alpine

# Set working directory
WORKDIR /

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Compile TypeScript code
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start application
CMD ["node", "build/index.js"]
